# Generated by Django 5.2.1 on 2025-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Felix_its', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='felixclass',
            name='type',
            field=models.CharField(choices=[('FSJ', 'FULLSTACKJAVA'), ('FSD', 'FULLSTACKDjango'), ('FSP', 'FULLSTACKPython'), ('FSC1', 'FULLSTACKC#'), ('FSC2', 'FULLSTACKC++'), ('FSC3', 'FULLSTACKC')], max_length=4),
        ),
    ]
